version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /api
    schedule:
      interval: weekly
    groups:
      python-security:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /sandbox
    schedule:
      interval: weekly
    groups:
      python-security:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    groups:
      ui-security:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
