target-version = "py312"
line-length = 100

[lint]
select = [
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "DTZ",
  "E4",
  "E7",
  "E9",
  "EXE",
  "F",
  "FLY",
  "FURB",
  "G",
  "I",
  "ISC004",
  "LOG",
  "PERF",
  "PIE",
  "PLR1711",
  "PT",
  "PTH124",
  "PTH210",
  "PYI",
  "RET",
  "RUF005",
  "RUF006",
  "RUF007",
  "RUF008",
  "RUF009",
  "RUF010",
  "RUF012",
  "RUF013",
  "RUF015",
  "RUF016",
  "RUF017",
  "RUF018",
  "RUF019",
  "RUF020",
  "RUF021",
  "RUF022",
  "RUF023",
  "RUF024",
  "RUF026",
  "RUF028",
  "RUF030",
  "RUF032",
  "RUF033",
  "RUF034",
  "RUF036",
  "RUF040",
  "RUF041",
  "RUF043",
  "RUF046",
  "RUF048",
  "RUF049",
  "RUF051",
  "RUF053",
  "RUF057",
  "RUF058",
  "RUF059",
  "RUF063",
  "RUF068",
  "RUF100",
  "RUF101",
  "RUF200",
  "S102",
  "S110",
  "S112",
  "SIM",
  "TRY002",
  "TRY004",
  "TRY401",
  "UP",
  "W",
  "YTT",
]

[lint.flake8-bugbear]
extend-immutable-calls = [
  "fastapi.Body",
  "fastapi.Cookie",
  "fastapi.Depends",
  "fastapi.File",
  "fastapi.Form",
  "fastapi.Header",
  "fastapi.Path",
  "fastapi.Query",
  "fastapi.Security",
]
