apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencitadel.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "opencitadel.fullname" . }}
data:
  config.yaml: |
{{ .Values.appConfig | toYaml | nindent 4 }}
