apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencitadel.fullname" . }}-execution-kernel-secret
  labels:
    app.kubernetes.io/component: execution-kernel
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.executionKernelPostgresPassword | quote }}
