{{- if .Values.opsActuator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencitadel.fullname" . }}-ops-actuator-secret
  labels:
    app.kubernetes.io/component: ops-actuator
type: Opaque
stringData:
  OPS_ACTUATOR_TOKEN: {{ .Values.opsActuator.token | quote }}
{{- end }}
