apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencitadel.fullname" . }}-migration-secret
  labels:
    app.kubernetes.io/component: migration
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresMigrationPassword | quote }}
