{{- if .Values.opsCollector.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencitadel.fullname" . }}-ops-collector-secret
  labels:
    app.kubernetes.io/component: ops-collector
type: Opaque
stringData:
  OPS_COLLECTOR_TOKEN: {{ .Values.opsCollector.token | quote }}
{{- end }}
