apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencitadel.fullname" . }}-execution-kernel-metrics
spec:
  selector:
    {{- include "opencitadel.selectorLabels" (dict "root" $ "component" "execution-kernel") | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.executionKernel.metricsPort }}
      targetPort: metrics
