"""Graded error codes for model / tool / infra failure domains."""

# Chat LLM domain
MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
MODEL_RATE_LIMITED = "MODEL_RATE_LIMITED"
MODEL_TIMEOUT = "MODEL_TIMEOUT"
MODEL_NOT_CONFIGURED = "MODEL_NOT_CONFIGURED"
MODEL_QUOTA_EXCEEDED = "MODEL_QUOTA_EXCEEDED"
MODEL_INVALID_REQUEST = "MODEL_INVALID_REQUEST"

# Embedding domain
EMBEDDING_UNAVAILABLE = "EMBEDDING_UNAVAILABLE"
DOCUMENT_PARSE_FAILED = "DOCUMENT_PARSE_FAILED"

# Tool / sandbox domains
TOOL_FAILED = "TOOL_FAILED"
SANDBOX_UNAVAILABLE = "SANDBOX_UNAVAILABLE"

# Platform infrastructure
INFRASTRUCTURE_FAILED = "INFRASTRUCTURE_FAILED"
