from typing import Protocol

from app.domain.models.artifact import Artifact


class ArtifactRepository(Protocol):
    async def save(self, artifact: Artifact) -> None: ...

    async def get_by_id(self, artifact_id: str) -> Artifact | None: ...

    async def list_by_session(self, session_id: str) -> list[Artifact]: ...

    async def get_by_share_token(self, token: str) -> Artifact | None: ...
