#!/usr/bin/env python
# -*- coding: utf-8 -*-
from datetime import datetime
from typing import Protocol, List, Optional

from app.domain.models.scheduled_job import ScheduledJob


class ScheduledJobRepository(Protocol):
    async def save(self, job: ScheduledJob) -> None: ...

    async def get_by_id(self, job_id: str) -> Optional[ScheduledJob]: ...

    async def get_by_webhook_token(self, token: str) -> Optional[ScheduledJob]: ...

    async def list_by_owner(self, owner_user_id: str) -> List[ScheduledJob]: ...

    async def list_due(self, now: datetime, limit: int = 20) -> List[ScheduledJob]: ...

    async def get_by_last_run_session_id(self, session_id: str) -> Optional[ScheduledJob]: ...

    async def delete_by_id(self, job_id: str) -> None: ...
