"""Finite synthetic role-shard writer; generated bytes are never runtime proof.

Rows arrive one at a time. Sharded roles permit a shard with one populated
family and all other list families empty; repeated scalar controls stay exact.
The product PackageSession remains the only validator of these test artifacts.
"""

import hashlib
import json
import os
import stat
from pathlib import Path

from scripts.acceptance.capacity_io import (
    MAX_ARTIFACT_BYTES,
    MAX_ARTIFACTS,
    MAX_PACKAGE_BYTES,
    SHARDED,
)

SHARD_TARGET_BYTES = 16 * 1024 * 1024


class FiniteRoleWriter:
    def __init__(
        self,
        root: Path,
        role: str,
        *,
        controls: dict,
        list_fields: tuple[str, ...],
        allow_empty=False,
    ):
        if (
            not root.is_absolute()
            or not root.is_dir()
            or stat.S_IMODE(root.stat().st_mode) != 0o700
            or role not in SHARDED
            or not list_fields
            or len(set(list_fields)) != len(list_fields)
            or set(list_fields) != SHARDED[role]
            or any(field in controls for field in list_fields)
            or controls.get("role") != role
            or controls.get("schema_version") != 3
            or type(allow_empty) is not bool
        ):
            raise ValueError("finite sharded role writer requires fixed private root/fields")
        self.root, self.role = root, role
        self.controls = controls.copy()
        self.fields = list_fields
        self._field = None
        self._rows = []
        self._rows_bytes = 0
        self._descriptors = []
        self._closed = False
        self._allow_empty = allow_empty

    def start(self, field: str):
        if self._closed or self._field is not None or field not in self.fields:
            raise ValueError("finite role field transition differs")
        self._field = field

    def append(self, field: str, row):
        if self._closed or field != self._field:
            raise ValueError("finite role field owner differs")
        raw = json.dumps(row, ensure_ascii=True, separators=(",", ":"), allow_nan=False).encode()
        if len(raw) > SHARD_TARGET_BYTES // 2:
            raise ValueError("finite role row exceeds per-shard working bound")
        if self._rows and self._rows_bytes + len(raw) + 1 > SHARD_TARGET_BYTES:
            self._flush()
        self._rows.append(raw)
        self._rows_bytes += len(raw) + 1

    def finish_field(self, field: str):
        if field != self._field:
            raise ValueError("finite role field closure differs")
        if self._rows:
            self._flush()
        self._field = None

    def _flush(self, *, allow_empty=False):
        if (
            (not self._rows and not allow_empty)
            or self._field is None
            or len(self._descriptors) >= MAX_ARTIFACTS
        ):
            raise ValueError("finite role shard closure/limit differs")
        prefix = json.dumps(
            self.controls, ensure_ascii=True, separators=(",", ":"), allow_nan=False
        )
        if prefix[-1:] != "}" or len(prefix) > 1024 * 1024:
            raise ValueError("finite role controls absent")
        parts = [prefix[:-1].encode()]
        for field in self.fields:
            parts.extend((b',"', field.encode(), b'":['))
            if field == self._field:
                parts.append(b",".join(self._rows))
            parts.append(b"]")
        parts.append(b"}")
        encoded = b"".join(parts)
        if len(encoded) > MAX_ARTIFACT_BYTES:
            raise ValueError("finite role shard exceeds product limit")
        ordinal = len(self._descriptors)
        name = f"{self.role}-{ordinal:04}.json"
        descriptor = os.open(
            self.root / name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600
        )
        try:
            length = 0
            while length < len(encoded):
                written = os.write(descriptor, encoded[length:])
                if written <= 0:
                    raise OSError("finite role write made no progress")
                length += written
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        self._descriptors.append(
            {
                "path": name,
                "sha256": hashlib.sha256(encoded).hexdigest(),
                "size_bytes": len(encoded),
                "role": self.role,
                "schema_version": 3,
                "shard_index": ordinal,
            }
        )
        self._rows.clear()
        self._rows_bytes = 0

    def close(self):
        if self._closed or self._field is not None:
            raise ValueError("finite role writer cannot close active family")
        if not self._descriptors:
            if not self._allow_empty:
                raise ValueError("empty sharded role requires explicit producer policy")
            # A role with zero rows still needs one complete schema-valid shard.
            # The shared parser decides whether the empty family is admissible.
            self._field = self.fields[0]
            self._flush_empty()
            self._field = None
        if (
            len(self._descriptors) > MAX_ARTIFACTS
            or sum(row["size_bytes"] for row in self._descriptors) > MAX_PACKAGE_BYTES
        ):
            raise ValueError("finite role aggregate exceeds product limit")
        count = len(self._descriptors)
        for row in self._descriptors:
            row["shard_count"] = count
        self._closed = True
        return tuple(self._descriptors)

    def _flush_empty(self):
        if self._rows or self._field is None:
            raise ValueError("empty shard requires a closed empty role")
        self._flush(allow_empty=True)
